### ISSUE TITLE
ImportError: No module named 'torch_spline_conv'

### ISSUE THREAD

**Issue by SeekPoint** [benedekrozemberczki/SGCN#1]
(.venv) ub16hp@UB16HP:~/ub16_prj/SGCN$ python src/main.py
Traceback (most recent call last):
  File "src/main.py", line 3, in <module>
    from sgcn import SignedGCNTrainer
  File "/home/ub16hp/ub16_prj/SGCN/src/sgcn.py", line 12, in <module>
    from torch_geometric.nn import SAGEConv
  File "/home/ub16hp/ub16_prj/SGCN/.venv/lib/python3.5/site-packages/torch_geometric/nn/__init__.py", line 1, in <module>
    from .conv import *  # noqa
  File "/home/ub16hp/ub16_prj/SGCN/.venv/lib/python3.5/site-packages/torch_geometric/nn/conv/__init__.py", line 1, in <module>
    from .spline_conv import SplineConv
  File "/home/ub16hp/ub16_prj/SGCN/.venv/lib/python3.5/site-packages/torch_geometric/nn/conv/spline_conv.py", line 3, in <module>
    from torch_spline_conv import SplineConv as Conv
ImportError: No module named 'torch_spline_conv'
(.venv) ub16hp@UB16HP:~/ub16_prj/SGCN$

**Comment by benedekrozemberczki** [comment]
Did You setup Pytorch Geometric properly?
